server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: ticketing_admin
    password: ticketing_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG